---
- type: language
  path: docs/examples
  label: list-docs
  create: all
  match: "**/*"
  new_doc_ext: ".yaml"
- type: directory
  path: docs/examples
  label: list-docs
  create: all
  match: "**/*"
  new_doc_ext: ".yaml"
- type: directory
  path: docs
  label: docs
  create: all
  match: "**/*"
