---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: list-docs
  create: all
  match: "**/*"
  new_doc_ext: ".yaml"
- type: directory
  path: docs
  label: docs
  create: all
  match: "**/*"
- type: directory
  path: articles
  label: articles
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
